#!/usr/bin/env bash
#Distribute traffic to web-01 & web-02 servers through lb-01 HAProxy


# Install & configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# append lb config to config file
config=\
"
frontend eke_front
        bind *:80
        mode http
        default_backend eke_back

backend eke_back
        balance roundrobin
        server 6444-web-01 3.82.215.250:80 check
        server 6444-web-02 34.205.127.228:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable init script startup for haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# confirm config is valid and restart haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
