#!/usr/bin/env bash
# Install nginx webserver on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# config redirection
sudo sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
