#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 Moved Permanently

# Update packages
apt-get -y update
apt-get -y install nginx

# Start nginx service
service nginx start

# Create index.html with "Holberton School" content
echo "Holberton School" > /var/www/html/index.html

# Configure Nginx redirection
sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
