#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

# Update packages
apt-get -y update
apt-get -y install nginx

# Start nginx service
service nginx start

# Create index.html with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx for redirection (from previous task)
sed -i '/server_name _;/a \\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Configure Nginx for custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
